import { getInstallationOctokit } from './client.js';

export interface CreatePullRequestParams {
  installationId: number;
  owner: string;
  repo: string;
  title: string;
  body: string;
  head: string;
  base: string;
}

export interface PullRequest {
  number: number;
  html_url: string;
  state: string;
}

export async function createPullRequest(params: CreatePullRequestParams): Promise<PullRequest> {
  const octokit = await getInstallationOctokit(params.installationId);

  const response = await octokit.pulls.create({
    owner: params.owner,
    repo: params.repo,
    title: params.title,
    body: params.body,
    head: params.head,
    base: params.base,
  });

  return {
    number: response.data.number,
    html_url: response.data.html_url,
    state: response.data.state,
  };
}

export async function getDefaultBranch(
  installationId: number,
  owner: string,
  repo: string
): Promise<string> {
  const octokit = await getInstallationOctokit(installationId);

  const response = await octokit.repos.get({
    owner,
    repo,
  });

  return response.data.default_branch;
}

export async function listPullRequests(
  installationId: number,
  owner: string,
  repo: string,
  head?: string
): Promise<PullRequest[]> {
  const octokit = await getInstallationOctokit(installationId);
  const params = {
    owner,
    repo,
    state: 'open' as const,
    ...(head ? { head: `${owner}:${head}` } : {}),
  };

  const response = await octokit.pulls.list(params);

  return response.data.map((pr) => ({
    number: pr.number,
    html_url: pr.html_url,
    state: pr.state,
  }));
}

export function formatPullRequestBody(issueNumber: number, sessionId: string): string {
  return `## Summary

This pull request was automatically generated by the Orcha agent.

Closes #${issueNumber}

---

**Session ID:** \`${sessionId}\`

*Generated by [Orcha](https://github.com/your-org/orcha) - GitHub issue-to-agent orchestrator*`;
}
